repos:
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: local
    hooks:
      - id: run-tests
        name: Run tests
        entry: pytest --maxfail=1 --disable-warnings -q tests/
        language: system
        types: [python]

      - id: pdoc-generate
        name: Regenerate pdoc docs
        entry: pdoc --output-dir docs swmaps
        language: system
        pass_filenames: false
