services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: swmaps
      POSTGRES_USER: swmaps
      POSTGRES_PASSWORD: swmaps
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib.postgresql/data

  api:
    build: .
    command: uvicorn swmaps.api:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: swmaps
      DB_USER: swmaps
      DB_PASSWORD: swmaps
    volumes:
      - .:/app
    depends_on:
      - db

  titiler:
      image: ghcr.io/developmentseed/titiler:latest
      ports:
        - "8001:8000"
      environment:
        - WORKERS_PER_CORE=1
        - HOST=0.0.0.0
        - PORT=8000
      volumes:
        - .:/data
      restart: unless-stopped
    
volumes:
  pgdata: