[project]
name = "swmaps"
version = "0.1.2"
dependencies = [
    "albumentations",
    "cloudml-hypertune",
    "dask",
    "earthengine-api",
    "fastapi",
    "flask",
    "geemap",
    "geopandas",
    "google-cloud-pubsub",
    "google-cloud-run",
    "google-cloud-storage",
    "httpx",
    "matplotlib",
    "numba",
    "numpy",
    "pandas",
    "pillow",
    "psycopg2-binary",
    "pydantic",
    "pydantic-settings",
    "python-dotenv",
    "rasterio",
    "requests",
    "rioxarray",
    "scikit-learn",
    "scipy",
    "segmentation_models_pytorch",
    "shapely",
    "torch",
    "torchgeo",
    "tqdm",
    "uvicorn",
    "xarray",
    "xgboost",
]

[tool.setuptools]
packages = { find = {} }
