"""Lookup table mapping CDL class identifiers to human-readable labels."""
CDL_CLASSES = {
    1: "Corn",
    2: "Cotton",
    3: "Rice",
    4: "Sorghum",
    5: "Soybeans",
    6: "Sunflower",
    10: "Peanuts",
    11: "Tobacco",
    12: "Sweet Corn",
    13: "Pop or Ornamental Corn",
    14: "Mint",
    21: "Barley",
    22: "Durum Wheat",
    23: "Spring Wheat",
    24: "Winter Wheat",
    25: "Other Small Grains",
    26: "Dbl Crop WinWht/Soybeans",
    27: "Rye",
    28: "Oats",
    29: "Millet",
    30: "Speltz",
    31: "Canola",
    32: "Flaxseed",
    33: "Safflower",
    34: "Rape Seed",
    35: "Mustard",
    36: "Alfalfa",
    37: "Other Hay/Non Alfalfa",
    38: "Camelina",
    39: "Buckwheat",
    41: "Sugarbeets",
    42: "Dry Beans",
    43: "Potatoes",
    44: "Other Crops",
    45: "Sugarcane",
    46: "Sweet Potatoes",
    47: "Misc Vegs & Fruits",
    48: "Watermelons",
    49: "Onions",
    50: "Cucumbers",
    51: "Chick Peas",
    52: "Lentils",
    53: "Peas",
    54: "Tomatoes",
    55: "Caneberries",
    56: "Hops",
    57: "Herbs",
    58: "Clover/Wildflowers",
    59: "Sod/Grass Seed",
    60: "Switchgrass",
    61: "Fallow/Idle Cropland",
    62: "Pasture/Grass",
    63: "Forest",
    64: "Shrubland",
    65: "Barren",
    66: "Cherries",
    67: "Peaches",
    68: "Apples",
    69: "Grapes",
    70: "Christmas Trees",
    71: "Other Tree Crops",
    72: "Citrus",
    74: "Pecans",
    75: "Almonds",
    76: "Walnuts",
    77: "Pistachios",
    81: "Clouds/No Data",
    82: "Water",
    83: "Wetlands",
    84: "Developed",
    85: "Developed/Open Space",
    86: "Developed/Low Intensity",
    87: "Developed/Med Intensity",
    88: "Developed/High Intensity",
    92: "Aquaculture",
    111: "Open Water",
    112: "Perennial Ice/Snow",
    121: "Developed/Open Space",
    122: "Developed/Low Intensity",
    123: "Developed/Med Intensity",
    124: "Developed/High Intensity",
    131: "Barren",
    141: "Deciduous Forest",
    142: "Evergreen Forest",
    143: "Mixed Forest",
    152: "Shrubland",
    176: "Grassland/Pasture",
    190: "Woody Wetlands",
    195: "Herbaceous Wetlands",
    204: "Pineapple",
    205: "Blueberries",
    206: "Cranberries",
    207: "Other Tree Fruits",
    208: "Cabbage",
    209: "Celery",
    210: "Radishes",
    211: "Garlic",
    212: "Spinach",
    213: "Carrots",
    214: "Asparagus",
    215: "Lettuce",
    216: "Turnips",
    217: "Eggplants",
    218: "Cantaloupes",
    219: "Squash",
    220: "Pumpkins",
    221: "Strawberries",
    222: "Dbl Crop WinWht/Corn",
    223: "Dbl Crop Oats/Corn",
    224: "Dbl Crop Barley/Corn",
    225: "Dbl Crop WinWht/Sorghum",
    226: "Dbl Crop Barley/Sorghum",
    227: "Dbl Crop WinWht/Cotton",
    228: "Dbl Crop Barley/Cotton",
    229: "Dbl Crop WinWht/Rice",
    230: "Dbl Crop Barley/Rice",
    231: "Dbl Crop WinWht/Other",
    232: "Dbl Crop Barley/Other",
    233: "Dbl Crop Soybeans/Corn",
    234: "Dbl Crop Soybeans/Sorghum",
    235: "Dbl Crop Soybeans/Cotton",
    236: "Dbl Crop Soybeans/Rice",
    237: "Dbl Crop Soybeans/Other",
    238: "Dbl Crop Corn/Soybeans",
    239: "Dbl Crop Cotton/Soybeans",
    240: "Dbl Crop Rice/Soybeans",
    241: "Dbl Crop Other",
    242: "Dbl Crop Barley/Soybeans",
    243: "Dbl Crop Oats/Soybeans",
    244: "Dbl Crop Corn/Cotton",
    245: "Dbl Crop Sorghum/Cotton",
    246: "Dbl Crop Soybeans/Vegetables",
    247: "Dbl Crop Corn/Vegetables",
    248: "Dbl Crop Cotton/Vegetables",
    249: "Dbl Crop Other/Vegetables",
    250: "Dbl Crop Soybeans/Sugarbeets",
    251: "Dbl Crop Soybeans/Corn/Sorghum",
    252: "Dbl Crop Soybeans/Corn/Cotton",
    253: "Dbl Crop Soybeans/Cotton/Corn",
    254: "Dbl Crop Soybeans/Cotton/Sorghum",
    255: "Missing Data",
}
