# =====================================================================
# TEMPLATE CONFIG FILE FOR RUN_WORKFLOW.PY
# This file documents all available options.
# Copy and edit this file to create region-specific configs.
# =====================================================================

# ---------------------------------------------------------------------
# Global settings
# ---------------------------------------------------------------------

# Path to AOI region (GeoJSON)
region = "config/somerset.geojson"

# Where outputs should be written (relative to project root)
output_root = "examples/somerset_landsat"

# ---------------------------------------------------------------------
# Missions and date ranges
# Each mission can have one or more date ranges in ISO8601 start/end
# format (YYYY-MM-DD/YYYY-MM-DD).
# Example below covers Landsat-5 and Landsat-7 historical periods.
# ---------------------------------------------------------------------
[missions]
landsat-5 = ["1990-07-01/1990-07-31", "2005-07-01/2005-07-31"]
landsat-7 = ["2000-07-01/2000-07-31", "2010-07-01/2010-07-31"]

# ---------------------------------------------------------------------
# Step profiles
# Define named profiles under [steps.<profile>] and enable/disable
# stages of the pipeline.
# You can have multiple profiles (somerset_demo, choptank_full, quick_test, etc.)
# and select them at runtime with --profile.
# ---------------------------------------------------------------------

[steps.demo]
coastal   = false     # skip coastal polygon creation
download  = true      # download imagery/mosaics
ndwi      = true      # generate NDWI water masks
trend     = false     # skip trend analysis
salinity  = true      # run salinity estimation
overlays  = true      # fetch NLCD/CDL overlays

[steps.full_pipeline]
coastal   = true
download  = true
ndwi      = true
trend     = true
salinity  = true
overlays  = false     # disable overlays if not needed

[steps.quick_test]
coastal   = true
download  = true
ndwi      = false
trend     = false
salinity  = false
overlays  = false

# ---------------------------------------------------------------------
# Parameters (shared across steps)
# ---------------------------------------------------------------------
[parameters]
# Water threshold used for NDWI and salinity masking
water_threshold = 0.2

# Number of STAC items per patch to request
max_items = 3

# NDWI center crop size (in pixels) for masks
center_size = 64

# Parallelism
multithreaded = false   # enable multi-threaded downloads
inline_mask   = false   # compute masks inline during download

# Optional salinity truth data
truth_dir  = ""         # directory containing .nc salinity files
truth_file = ""         # CSV file with salinity observations

# Overlay year (for NLCD/CDL fetches)
overlay_year = 2005
